### ISSUE TITLE
Wrong bodySize (and feature request: add _transferSize)

### ISSUE THREAD

**Issue by c0b** [cyrus-and/chrome-har-capturer#25] opened 2016-05-09 19:35 UTC
I'm test-running `timing-fix` branch code, found there are still a few fields missing from this chrome-har-capturer than a real Chrome DevTools, one is request headers, I can only see `Referer` and `User-Agent` while a real Chrome DevTools gives all headers sent in full, like `Host: ...`, `Accept-Encoding: ...` and others, I haven't looked at the chrome remote debugging protocol, not even sure if remote-interface ever provided those, or can it be done in this chrome-har-capturer ??

```json
          "headers": [
            {
              "name": "Referer",
              "value": "http://www.podcastone.com/widgetrecent?progID=877"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2716.0 Safari/537.36"
            }
          ],
```

Another one I found from a real Chrome DevTools is the `_transferSize`; when in `transfer-encoding: chunked` mode, the response is (a length + a chunk) + (length + chunk) + ... + 0; so the real transferred bytes on the wire could be slightly larger than `bodySize`; I'm not sure which har viewer ever take use of the `_transferSize` but it can be used in real bandwith calculation or something, and it's missing from this chrome-har-capturer

```json
          "content": {
            "size": 118465,
            "mimeType": "text/html",
            "compression": 96200
          },
          "redirectURL": "",
          "headersSize": 662,
          "bodySize": 22265,
          "_transferSize": 22927
```

**Comment by c0b** [comment] 2016-05-09 19:54
or the transferred bytes on tcp connection

**Comment by cyrus-and** [comment] 2016-05-10 18:47
For what concerns the headers, I'm afraid that this is a limitation of Chrome and it seems that it only applies to the request headers, while I get all the response headers. Can you confirm this?

I simply use [request.headers][1] and [response.headers][2]; inserting some debug prints as soon as the event is handled shows (unsurprisingly) the same headers that appear in the HAR file. You may want to try to file an issue to Chromium for this or dig into its source code.

[1]: https://chromedevtools.github.io/debugger-protocol-viewer/Network/#type-Request
[2]: https://chromedevtools.github.io/debugger-protocol-viewer/Network/#type-Response

---

> so the real transferred bytes on the wire could be slightly larger than bodySize

This is already taken into consideration since each [`dataReceived`][3] event contains both `dataLength` and `encodedDataLength`.

The body size has always been a tricky point... To my knowledge:

- `content.size` is the *unencoded* body size;
- `bodySize` is the encoded (*on the wire*) body size;
- `content.compression` is thus `content.size` - `bodySize`.

The problem is that summing up all the data chunks ([`encodedDataLength` field][3]) doesn't make the body size as reported by `content-length` and hence `content.compression` is wrong as well. I don't want to rely on that optional header. Note that the [`encodedDataLength` field][4] of the `loadingFinished` event yields the same result. I suspect  this is another Chromium bug.

[3]: https://chromedevtools.github.io/debugger-protocol-viewer/Network/#event-dataReceived
[4]: https://chromedevtools.github.io/debugger-protocol-viewer/Network/#event-loadingFinished

---

Before adding custom fields I'd like to fix `compression` and `bodySize`. Anyway, is `_transferSize` really useful? I mean, it can be derived pretty easily by the formula you wrote. But if it really includes all the other overheads you mentioned (which I don't think so) I really don't know how to fetch them. The fact is that it is not properly documented.

**Comment by c0b** [comment] 2016-05-10 20:10
> while I get all the response headers. Can you confirm this?

yes I can confirm response headers are complete;

request headers are always incomplete, if chrome never exposed that full headers, that is sad and seems no way to fix?

> The fact is that it is not properly documented.

I agree large part of [this protocol](https://developer.chrome.com/devtools/docs/protocol/1.1/index) is not properly documented; Digging in the source code https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools could be useful in some cases

**Comment by c0b** [comment] 2016-05-13 20:20
@cyrus-and I'm looking at more details at `Network.responseReceived` message, its response obj has the actual sent headers, here is an example what I got from `console.dir(params, {depth: null})` on a `Network.responseReceived` message; I believe this part can be improved, use `response.requestHeaders` at response received time instead of `Network.requestWillBeSent` time,

{ requestId: '32736.165',
  frameId: '32736.1',
  loaderId: '32736.3',
  timestamp: 5479128.344171,
  type: 'Image',
  response: 
   { url: 'http://............',
     status: 200,
     statusText: 'OK',
     headers: 
      { Pragma: 'no-cache',
        Date: 'Fri, 13 May 2016 20:03:48 GMT',
        Server: '...',
        ...

     headersText: 'HTTP/1.1 200 OK\r\n...',
     mimeType: 'image/gif',
     requestHeaders: 
      { 'Accept-Encoding': 'gzip, deflate, sdch',
        Host: '...',
        'Accept-Language': 'en-US,en;q=0.8',
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36',
        Accept: 'image/webp,image/*,*/*;q=0.8',
        Referer: '...',
        Cookie: '...',
        Connection: 'keep-alive' },
     requestHeadersText: 'GET /...',
```

I think this makes sense because at `Network.requestWillBeSent` time, no packet is going on wire yet, it doesn't know completely yet all the headers will be sent, or can this be counted as a bug of the protocol? because requestWillBeSent is not called at the moment right before going on wire, it happened much earlier

**Comment by cyrus-and** [comment] 2016-05-13 20:37
Sounds reasonable, I'm now using that field, but falling back to the original if not present. Probably that would never happen but [`requestHeaders`][1] is marked as *optional*. Thank you!

[1]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#type-Response

**Comment by cyrus-and** [comment] 2016-06-01 17:17
So to summarize, the header problem is fixed now. While the `bodySize` (i.e., the *on the wire* body size) is reported incorrectly by Chrome. For example:

```
$ curl -s -H 'Accept-Encoding: gzip' http://example.com/ | wc -c
606
```

Which is also the value reported in the `Content-Length` header, is the correct one. While the HAR reports:

```
"headersSize": 372,
"bodySize": 978,
"content": {
    "size": 1270,
    "mimeType": "text/html",
    "compression": 292
}
```

Compared to the HAR generated by DevTools directly:

```
"headersSize": 372,
"bodySize": 606,
"content": {
  "size": 1270,
  "mimeType": "text/html"
  "compression": 664
},
"_transferSize": 978
```

Note that in both cases `compression` satisfies:

```
compression = size - bodySize
292 = 1270 - 978
664 = 1270 - 606
```

**Comment by cyrus-and** [comment] 2016-06-01 18:21
I finally submitted an [issue][1] to Chromium.

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=616546

**Comment by cyrus-and** [comment] 2016-06-09 20:23
OK, fixed. It seems that `encodedDataLength` represents the encoded payload **plus** the headers.
I also added `_transferSize`.

**Closed** 2016-06-09 21:13 UTC
Labels: bug, enhancement
