### ISSUE TITLE
Separate HAR file and consecutive load error

### ISSUE THREAD

**Issue by sjfricke** [cyrus-and/chrome-har-capturer#42] opened 2017-04-18 18:49 UTC
So this whole issue stems from the fact I can't do a `require('chrome-har-capturer').load(large_list);` as I have found there becomes a point where it can't handle the buffer to write the HAR output and I have a list of like 1000 sites I need to HAR scrape. Since I can't use a long array the *hack* around is to use recursion like this

```
var fs = require('fs');
var chc = require('chrome-har-capturer');
var list = ["https://github.com", "https://www.reddit.com"];

function loadSite(i) {
    if (i >= list.length) return; //ends recursion

    var c = chc.load(list[i]);

    c.on('connect', function () {
        console.log("Connected to Chrome: " + i);
    });
    c.on('end', function (har) {
        console.log("Done: " + i);

//	loadSite(++i); // uncomment to see Invalid tab index

//	setTimeout(function(){ loadSite(++i) }, 100); // uncomment to see it NOT have error

    });
    c.on('error', function (err) {
        console.error("Cannot connect to Chrome: " + err);
    });
}

// Kicks off recursion
loadSite(0);
```

The issue is chrome takes like 50ms when opens a new tab to populate the `devtoolsFrontendUrl` and `webSocketDebuggerUrl` properties.

I guess the **real** question is there is **two** ways of dealing with this

1.  
- Most people are probably not going to need to scrape hundreds of sites at once and can just parse with the page reference when passed an array and leave the `setTimeout` as a unique case hack 
- It would be nice to have separate HAR files in general if you had like just 5 separate sites and didn't want them all merge. So maybe have a parser built in to prevent people from keep making their own

2. 
- Have a quick (50-100ms) *check again* feature in the check for the [webSocketDebuggerUrl](https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/chrome.js#L18)
    - Something where it calls again before throwing the error
    - I notice that the NPM module isn't updated so the current issue is [fetchDebuggingUrl function](https://github.com/cyrus-and/chrome-remote-interface/blob/a2dd75fa8c299473b2e1afcbb005aa6139a2efb1/lib/chrome.js#L166) 

I would be happy to make the changes and submit the PR, but wanted to get your opinion on the subject first

**Comment by cyrus-and** [comment] 2017-04-18 23:31
Before digging into the timeout issue I have a couple of questions.

> becomes a point where it can't handle the buffer to write the HAR output

What happens exactly, is this a problem with the JSON stringification of a massive object or the array length itself? Can you reliably reproduce it?
I've tried locally with the following but I cannot trigger any error, maybe I need more data...

```js
var chc = require('chrome-har-capturer');
var http = require('http');
var fs = require('fs');

const server = http.createServer((req, res) => {
    console.log(`> ${req.url}`);
    if (req.url === '/') {
        const scripts = [];
        for (let i = 0; i < 1000; i++) {
            scripts.push(`<script src="/${i}"></script>`);
        }
        res.end(scripts.join('\n'));
    } else {
        res.end('/*...*/');
    }
}).listen(8000, () => {
    const list = Array(100).fill('http://localhost:8000');
    chc.load(list, {force: true})
        .on('end', (har) => {
            const json = JSON.stringify(har);
            fs.writeFileSync('/tmp/out.har', json);
            server.close();
            console.log('-- DONE --');
        })
        .on('error', (err => console.error(err)));
});
```

I even tried doing fake work with an array of 10k entries and the fake HAR is produced anyway.

> I notice that the NPM module isn't updated so the current issue is fetchDebuggingUrl function

What do you mean? Both modules are properly published to NPM and this one requires `0.x.x`.

> It would be nice to have separate HAR files in general if you had like just 5 separate sites and didn't want them all merge. So maybe have a parser built in to prevent people from keep making their own

Since the file writing is not a part of this library why not just submit batches of URLs to the library and then save the files separately? In this case you'll have a `chc.load()` for each batch.

Also what parser?

**Comment by cyrus-and** [comment] 2017-04-18 23:36
For what concerns the timeout issue I think it happens because the `end` event is emitted before the actual close. This should be easily fixed with:

```diff
diff --git a/lib/client.js b/lib/client.js
index 12669d6..8c08ae9 100644
--- a/lib/client.js
+++ b/lib/client.js
@@ -114,11 +114,12 @@ function Client(urls, options) {
                     }
                 });
             } else {
-                // no more URLs to process
-                self.emit('end', har.create(pages));
                 // load the neutral URL then exit
                 chrome.Page.navigate({'url': NEUTRAL_URL}, function (error, response) {
-                    chrome.close();
+                    chrome.close(function () {
+                        // no more URLs to process
+                        self.emit('end', har.create(pages));
+                    });
                 });
             }
         }
```

**Comment by sjfricke** [comment] 2017-04-19 12:00
> becomes a point where it can't handle the buffer to write the HAR output

So I will run a second test, but essentially I had and array of 1500 with of websites in my `load()` call and the computer running it wasn't the newest/greatest in specs and after like 3 hours of getting all the sites it just errored out for what I presumed was from the oversize buffer of holding a JSON object that large as it worked with a subset of that 1500 list, I will add more logging and run it again but its a matter of running the long test.

> I notice that the NPM module isn't updated so the current issue is fetchDebuggingUrl function

I apologize as I didn't realize that `1.91` had 2 commits behind `lib/chrome.js`, these were really recent changes

**Comment by sjfricke** [comment] 2017-04-19 12:05
The issue was I wanted a separate HAR file per site

I was going to run a separate `load()` on each one but then found I needed to give a pause but this [has been fixed](https://github.com/cyrus-and/chrome-har-capturer/commit/57f26f984954baaa2696cef2d33a64162cf1a3a6)

There is **no** need for a parsing as my recursive calling in init issue message will work with this commit

Let me just rerun a long test and if it works then there is no need to keep this issue open

**Closed** 2017-04-19 12:05 UTC

**Comment by sjfricke** [comment] 2017-04-19 12:07
I am still going to run a test against my 1500 sites in a single `load()` and make an appropriate issue for it separately if I find it to still be an issue, I don't have the older computer, but will still be valid to just rerun it in general

**Comment by cyrus-and** [comment] 2017-04-19 12:13
OK, I'm really interested in figuring out why such error would happen. Thanks for your time!

**Comment by sjfricke** [comment] 2017-04-20 14:39
I ran the huge list again, granted it was ~250MB large of a file it worked. It was probably the fact my old machine was a Raspberry Pi 3 and that's a solid 1/4 of the RAM right there.
