### ISSUE TITLE
All logged timings are incorrect, and some other data too.

### ISSUE THREAD

**Issue by Fleshgrinder** [cyrus-and/chrome-har-capturer#19] opened 2015-05-27 09:08 UTC
Just compare a HAR exported with Chrome with a HAR exported with chrome-har-capturer and you are going to notice huge differences. The following diff shall illustrate that (omitted some parts for brevity). One issue I can directly point you to is [here](https://github.com/cyrus-and/chrome-har-capturer/blob/master/lib/har.js#L70) where you add the SSL/TLS time to the total time. This is wrong because, as per HAR specification, the connect time already includes the SSL/TLS time. There are many more differences between the files.

I am afraid that any logs created with this tool are incorrect and you should warn your users about this until the issue is fixed.

```diff
--- chrome-capturer.har	Wed May 27 10:25:13 2015
+++ chrome.har	Wed May 27 10:25:07 2015
@@ -1,21 +1,21 @@
 […]
-"time": 243.0489062498805,
+"time": 64.56995010375977,
 "request": {
     "method": "GET",
     "url": "https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.dPxK-DAj_pE.O/m=gapi_iframes,googleapis_client,plusone/rt=j/sv=1/d=1/ed=1/am=AAQ/rs=AItRSTN0fuoBkyFaoHWfzWWLct0BxZgQSQ/cb=gapi.loaded_0",
-    "httpVersion": "HTTP/1.1",
+    "httpVersion": "unknown",
 […]
 "response": {
     "status": 200,
     "statusText": "OK",
-    "httpVersion": "HTTP/1.1",
+    "httpVersion": "unknown",
 […]
 "timings": {
-    "blocked": -1,
-    "dns": 0.654000000054114,
-    "connect": 53.30499999990936,
-    "send": 1.0790000000042994,
-    "wait": 112.32899999993191,
-    "receive": 36.00390625,
-    "ssl": 39.677999999980806
+    "blocked": 0.974000000041997,
+    "dns": -1,
+    "connect": -1,
+    "send": 0.570000000038813,
+    "wait": 30.76099999998409,
+    "receive": 32.264950103694865,
+    "ssl": -1
 […]
```

**Comment by cyrus-and** [comment] 2015-05-27 12:21
Yes there are certainly some issues with the timings, let's see if I can recap.

###  `httpVersion`
Currently this is hardcoded to `HTTP/1.1`, it did make sense at the time. Now with HTTP/2 and QUIC I probably should fix that, but Chrome does not seem to propagate such information through the protocol.

### `time`
The connect time already includes the SSL/TLS time, it's true, but we'are not sure that even [the connect time returned by Chrome](https://developer.chrome.com/devtools/docs/protocol/1.1/network#type-ResourceTiming) does that. So according to this, it's the `connect` timing that would be wrong since it should include the SSL/TLS time, but the total time (`time`) remains the same.

### `blocked`
This timing is not directly exported by Chrome and I really don't know how to calculate it, so for the time being is always `-1`.

### `dns` and `connect`
These two timings are taken *verbatim* from Chrome, differences here may be due to the DNS cache or to the connection pool, which are not properly flushed. Or maybe they are simply returned incorrectly by Chrome.

### `wait` and `receive`
Neither these timings are directly exported by Chrome, currently they are computed as follows:

```
wait = timing.receiveHeadersEnd - timing.sendEnd
receive = object.responseFinishedMs - (timing.requestTime + timing.receiveHeadersEnd)
```

The idea behind this is that the waiting time is the time between the end of the request sending and (in the absence of a better metric) when response headers are received. Whereas, the receive time is the time between when the headers are received and the end of the response.

--

Unfortunately, I'm fighting against the lack of documentation/information provided by Chrome and all my attempts to write test cases to reproduce and compare these timing issues in a reliable way are failed; poor documentation and hence unexpected core changes in the information exposed by Chrome make this a very frustrating task.

Any help is obviously welcome, and thanks for reporting this.

**Comment by Fleshgrinder** [comment] 2015-05-27 12:28
Chrome is also logging _unknown_ in case of SPDY, as you can see in the provided diff. You could do the same. QUIC should never be in there, possible values are: HTTP, HTTP/1.0, HTTP/1.1, HTTP/2, and SPDY

As far as the time is concerned, this is intentional per the specification (emphasize mine):

> ssl [number, optional] (new in 1.2) - Time required for SSL/TLS negotiation. *If this field is defined then the time is also included in the connect field (to ensure backward compatibility with HAR 1.1)*. Use -1 if the timing does not apply to the current request.
—  [W3C Web Performance HAR Draft](https://w3c.github.io/web-performance/specs/HAR/Overview.html#timings)

Regarding everything else you said, I fully understand your frustration with it. I also think that the documentation and API of Chrome is lacking *a lot!* We can just hope that this is getting better in the future. You should still include a warning in your README file until at least the basic timing issues are resolved.

**Comment by cyrus-and** [comment] 2015-05-27 13:59
> QUIC should never be in there

I don't know, according to DevTools there are several options for the protocol: `quic/1+spdy/3`, `h2`, `spdy/3.1`, etc. So the presence of QUIC seems to me a valuable information, didn't read any spec though. In any case all the above protocols seems to be logged as `unknown` by Chrome.

The point is that I don't know how to check that, apart from looking for related HTTP headers, but I don't think it's an elegant solution.

--

Yes, I read the HAR spec, I was just saying that we don't know whether the connect time reported by Chrome includes the SSL/TLS negotiation or not:

> connectEnd ( number ) Connected to the remote host.
> connectStart ( number ) Started connecting to the remote host.
> sslEnd ( number ) Finished SSL handshake.
> sslStart ( number ) Started SSL handshake.

so the solution is to remove `sslTime` from the [sum](https://github.com/cyrus-and/chrome-har-capturer/blob/b48689a0946174bbbd22c50acbd17ba1dfad4e98/lib/har.js#L70) and add it to `connectTime` instead. My point was that after this fix the total time (rightfully) does not change, yet it appears to be suspiciously large.

--

A warning in the README seems reasonable, I'll try to keep this issue as a reference.

**Comment by Fleshgrinder** [comment] 2015-05-27 14:07
Combinations like the ones you just posted make sense. QUIC is part of the application protocol and referencing it as an attribute of the actual protocol is reasonable.

Inspecting headers is definitely a valid approach, and as it seems the only possible one.

My calculations with thousands of archives which were exported with Chrome showed that the connect time actually includes the SSL/TLS time, as per specs, in the HAR that you can export with the developer tools (either manually or the API version for extensions). It is questionable what Chrome reports via the remote API. Only solution would be to file a bug and ask.

**Comment by teddychua** [comment] 2016-03-16 08:13
This [chromium commit](https://groups.google.com/a/chromium.org/forum/#!topic/blink-checkins/WpXO1PyG8YM) defines what we see in the chrome dev tool, I think. So blocking is defined as `firstPositive([timing.dnsStart, timing.connectStart, timing.sendStart]); `
and receive is defined as:
`request.responseReceivedTime - timing.requestTime`

**Comment by teddychua** [comment] 2016-03-17 12:07
StartDateTime for entries are also incorrect.

**Comment by teddychua** [comment] 2016-03-18 04:39
I think I've fixed blockedTime, StartDateTime for entries, and the totalTime in a fork as of [8b3eee4](https://github.com/teddychua/chrome-har-capturer/commit/8b3eee4febb3122562d687c81f50b54840a3686f).

**Comment by cyrus-and** [comment] 2016-03-19 15:13
@teddychua thanks for the effort and the valuable information. I need to better look into this, but there are a some quick considerations.

* First of all, the code at teddychua@8b3eee4febb3122562d687c81f50b54840a3686f fails to execute; `page.originalRequestDate` is `undefined` [here][1].

* I don't know if it's legit to use the [resource timing API] as a reference. To my understanding there are like 4 *interpretations* of what the meaning of "timings" is:

    * JavaScript timing API;
    * [Har spec];
    * network panel timing information in DevTools;
    * [ResourceTiming] object available via the debugging protocol.

  Now the network panel timing information (described [here][resource timing API]) claims to use "the same Resource Timing API that is available to application developers"; yet this does not means that since Chromium is including the SSL time in the connect time there, it is doing the same in the [ResourceTiming] object.

    In other words the Chromium commit you provided shows how to build the timing graph from a [ResourceTiming] object (although I'm not entirely sure that it is exactly *that* object...). What we want instead is to derive HAR-specific timings from a [ResourceTiming] object. And this seems to be implemented somewhere starting at [HARWriter.js], I have not investigated yet...

* Before merging any code I'd like to setup a proper test case in order to highlight the differences among the current implementation, the "Copy All as HAR" and the candidate fix.

[1]: https://github.com/teddychua/chrome-har-capturer/blob/8b3eee4febb3122562d687c81f50b54840a3686f/lib/har.js#L28
[resource timing API]: https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/understanding-resource-timing
[HAR spec]: http://www.softwareishard.com/blog/har-12-spec/#timings
[ResourceTiming]: https://developer.chrome.com/devtools/docs/protocol/1.1/network#type-ResourceTiming
[HARWriter.js]: https://chromium.googlesource.com/chromium/blink.git/+/master/Source/devtools/front_end/network/HARWriter.js

**Comment by cyrus-and** [comment] 2016-03-19 16:48
I tried to mimic the implementation used by DevTools to produce the HAR entries ([HAREntry.js]).
Changes are confined in [timings-fix] for now.

[timings-fix]: /cyrus-and/chrome-har-capturer/tree/timings-fix
[HAREntry.js]: https://chromium.googlesource.com/chromium/blink.git/+/master/Source/devtools/front_end/sdk/HAREntry.js

**Comment by cyrus-and** [comment] 2016-06-09 21:16
I'm closing this for now; feel free to reopen it if you notice something wrong.

**Closed by cyrus-and** 2016-06-09 21:16 UTC
Labels: bug
